# Site settings
title:          mgc ht
description:    "just a oier's blog"
baseurl:        "/"
url:            "https://www.magichut.pw"

# Author
author:
  name:         KingSann
  url:          https://www.magichut.pw
  email:        me@magichut.pw

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
